"""adding acccount activation

Revision ID: 778294f5810e
Revises: 921bca1dad13
Create Date: 2024-01-04 11:37:34.232828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778294f5810e'
down_revision = '921bca1dad13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activated', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('activation_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('activation_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activation_sent_at')
    op.drop_column('users', 'activation_hash')
    op.drop_column('users', 'activated')
    # ### end Alembic commands ###
